name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d testdb" 
          --health-interval 5s --health-timeout 5s --health-retries 20
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" 
          --health-interval 5s --health-timeout 5s --health-retries 10

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Wait for Postgres
      run: |
        for i in `seq 1 30`; do
          pg_isready -h localhost -p 5432 -U postgres && break || sleep 1
        done

    - name: Install dependencies
      run: npm ci

    - name: Run migrations
      run: npm run migrate || echo "No migrate script defined"

    - name: Seed DB
      run: npm run seed || echo "No seed script defined"

    - name: Run tests
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_NAME: testdb
      run: npm test
